"""Initial baseline migration.

This baseline is metadata-driven: it creates (and drops) the full schema from
``Base.metadata``. Because the application models are the single source of
truth, this guarantees the migrated schema always matches the ORM models.
Subsequent schema changes should be captured as incremental autogenerated
revisions on top of this baseline.

Revision ID: de8b5e165733
Revises:
Create Date: 2026-04-03 16:36:45.114594
"""
from typing import Sequence, Union

from alembic import op

# Importing the models package registers all tables on Base.metadata.
import app.models  # noqa: F401
from app.models.base import Base

# revision identifiers, used by Alembic.
revision: str = "de8b5e165733"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create the complete schema from the ORM metadata."""
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    """Drop the complete schema."""
    Base.metadata.drop_all(bind=op.get_bind())
